= Entries 103-108

[arabic,start="121"]
. Heinrich Eduard +
geb: den 25ten October u. get. den 3ten November 1872. +
Eltern:
* Heinrich Rückler 
* Heinrich Rückler
L. Fridricka, geb. Dauner

+
Pathen: Jac Stochrjun. u. Georg Blum.
. Heinrich Friedrich. +
geb: den 20ten November u. get: den 23 November 1872. +
Eltern:
* Carl Grote
* Carolina, geb. Krückeberg.

+
Pathen: Heinrich Heier, u. Carl Krickeberg
. Emilia Paulina +
geb: den 17. November u. get: den 24 November 1872. +
Eltern:.
* Patrick Danahoe
* Therese, geb. Büttner

+
Pathen: Johana Christina Buttner u. Emilia Büttner.
. Georg Christian Wilhelm +
geb: d.n. 29ten Dezember, geb: den 5 Januar 1873 +
Eltern:
* Conrad Fells
* Carolina, geb. Peldner

+
Pathen: Wilhelm Fells u. Georg Blum
. Amalia Emilie Christina +
geb: den 15ten Febr: u. get. den 23 Febr. 1873. +
Eltern:
* August Hauph
* Dores geb. Danel

+
Pathen: Amalia Thieme u. Christina Buttner
. Friedrich Heinrich Wilhelm +
geb: den 5ten April u. get. den 20ten April 1873. +
Eltern:
* Wilhelm Schamerloh
* Chat. Margaretha, geb. Paas. †.(soll heißen Philipine Knruckeberg)

+
Pathen: Heinrich Krükeberg u. Wilh. Weiland.
