= Page ??
:page-role: doc-width

. Aldolph Johannes +
geb. den 14. Sept 1890 geb. d. 21. Sept. 1890
Eltern:
* Mme Bleeke
* Louise geb. Holle

+
Pathen: Kied. Holle, H. Reinking, Johannes Ehrmann +
H. Schmidt
. Paul Johann Heinrich, +
geb. den 16. Sept: 1890 getauft den 21. Sept. 1890 +
Eltern:
* Fred. Bleeke jun.
* Elise geb. Fülling

+
Pathen:Heinrich Füllin, und Hoy. Blecke. +
Schmidt
. Almida Karoline +
geb. d. 7. Okt. 1890 getauft den 19. Oktober 1890 +
Eltern:
* Friedich Weyland
* Louise geb. Schönstedt

+
Pathen: Karoline Weyland & Korline Grole??????? +
H Schmidt.
. Richard Theodor +
geb. d. 9. Okt. 90 gut d. 19. Okto. 1890 +
Eltern:
* Fr. Thieme
* Soph. Krückeberg.

+
Pathen: Fr. Krückeberg + Theodor Thume +
Schmidt
. Klara Elise Pauline. +
geb. d. 10. Okt. 1890 gut d. Okt 1890 +
Eltern: 
* Heinrich Bleeke
* Emilie geb. Thieme
Pathen: Elise Blecke, Pauline Bleeke +
Schmidt.
. Mabel Emilie +
geb. den 18. Aug. 90. getauft d. 12. Okt. 1890 +
Eltern:
* August Büttier
* Anna geb. Roth
Pathen: Emilie Rotti, Johanne Schmid +
H. Schmid.
