= Page 90, Entriesd== 79-84
[arabic,start="79"]
. Conrad Christian Wilhelm
geboren den 29ten Februar Vormittags 11 Uhr getauft den 1ten März 1868.
Christian Wilhelm Fells.
Eltern
Elisabeth geb. Rup
Pathen: Christian Bleeke, und Conrad Fells.
. Caroline Wilhelmine Bernhardine
geboren den 2ten May 1868 getauft den 10ten May 1668
Carl Heinrich Ludwig Koldewey
Eltern.
Louise Sophie geb: Winkelmann.
Pathen: Bernhardine Koldewey u. Wilhelmine Schamerloh.
. Martin Andreas Wilhelm
geboren den 3ten Mar Morgens 1 1/2 Uhr getauft den 10ten May 1868.
Conrad Dietrich Ferdinand Reinking
Eltern.
Maria Louise Eleonore geb. Bleeke.
Pathen: Wilhelm Heckmann, Andreas Thieme u. Wilhelm Reinking
. Sahra Isabella
geboren den 10 April 1868, getauft den 4ten Octobr 1868
Levi Baron
Eltern
Wilhelmine geb. Höreger.
Pathen: Jacob Fridrich Höreger u. dessen Ehefrau Maria.
. Sahra Catharine Sophie
geboren den 13ten October 1868. u. getauft den 25ten Oktober 1868
Heinrich Jakob Rücklos
Eltern
Friderike geb. Dauer.
Pathen: Jungfr. Sahra Belz u. Jungfr: Sophie Bleeke.
. [no name is present]
geboren den 17ten October 1868 u. getauft den 12 November 1868
Georg Blum
Eltern
Catharina geb. Feldner
Pathen: Conrad Fells und Jakob Stöhr

