= Entries 85-90

. Heinrich Friedrich Wilhelm
geboren den 21 September u. getauft den 2 October 1870
Eltern:
Ludwig Koldewy u.
Jakkia, geb. Cordes

+
Pathen: Friedrich Thiele u. Wilhelm Engelbrecht
. Christina Paulina.
geb: den 3 October und art. den 9ten October 1870.
Eltern:
(Gottfried Thieme)
Amalia, geb.

+
Pathen: Darothea Haugh u. Christina Büttner.
. Clara Maria
geb: den 1. Januar u. get. den 8ten Januari 1871.
Eltern
Andreas Thieme
Sophia, geb. Klein

+
Pathen: Amalia Thieme u. Carolina Schamerloh.
. Friedrich Fe
geb: den 12. Februar u. get. den 26 Febuar 1871.
Eltern:
Hanrich Rucklos
Friedricka, geb. Dauner

+
Pathen: Friedrich Bleeke u. Ferdinand Reinking.
. Sophia Christi
geb. den 22 Februar u. get. den 5 März 1871.
107
gelegten mich.
geb. den 6. April 1841.
Eltern
Wilhelm Eduard
Consed Falls
get. den 15. Apr. 21.
Carolina, geb. Feldner.
Eltern: Ch. Blecke, Maria
Pathen: Sophia Thience u. Christina Büttner
Pathen H. Plectle
Rup
Ed. Heckmann
Anna Maria Sophia
108,
get; durch P. Rupprecht
geb: den 26 Maerz u. get. den 9te April 1871.
eingetragen von St. G.
Eltern L. Wilhelm Schamerloh
Philippine, geb. Kruckeberg
Pathen: Maria Bleeke, Sophia Grote.
