{"level":"error","time":1751477528948,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/ROOT/pages/image118.adoc"},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"target of image not found: 118.jpg"}
{"level":"warn","time":1751477529275,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/ROOT/pages/image67.adoc","line":53},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected A, got H"}
{"level":"warn","time":1751477529278,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/ROOT/pages/image67.adoc","line":97},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected A, got H"}
{"level":"warn","time":1751477529294,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/ROOT/pages/image69.adoc","line":62},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected A, got U"}
{"level":"warn","time":1751477529303,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/ROOT/pages/image70.adoc","line":7},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"unterminated table block"}
{"level":"warn","time":1751477529310,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/ROOT/pages/image70.adoc","line":133},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"unterminated example block"}
{"level":"error","time":1751477529310,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/ROOT/pages/image70.adoc","line":133},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"dropping cells from incomplete row detected end of table"}
{"level":"warn","time":1751477529383,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/ROOT/pages/image84.adoc","line":7},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected A, got H"}
{"level":"warn","time":1751477529384,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/ROOT/pages/image84.adoc","line":31},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected B, got H"}
{"level":"warn","time":1751477529384,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/ROOT/pages/image84.adoc","line":44},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected C, got G"}
{"level":"warn","time":1751477529384,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/ROOT/pages/image84.adoc","line":45},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected D, got H"}
{"level":"warn","time":1751477529384,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/ROOT/pages/image84.adoc","line":46},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected E, got W"}
{"level":"warn","time":1751477529423,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/ROOT/pages/image92.adoc","line":23},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"unterminated literal block"}
{"level":"error","time":1751477529459,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/r/pages/image118.adoc"},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"target of image not found: 118.jpg"}
{"level":"warn","time":1751477529748,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/r/pages/image67.adoc","line":53},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected A, got H"}
{"level":"warn","time":1751477529750,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/r/pages/image67.adoc","line":97},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected A, got H"}
{"level":"warn","time":1751477529765,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/r/pages/image69.adoc","line":62},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected A, got U"}
{"level":"warn","time":1751477529773,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/r/pages/image70.adoc","line":7},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"unterminated table block"}
{"level":"warn","time":1751477529779,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/r/pages/image70.adoc","line":133},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"unterminated example block"}
{"level":"error","time":1751477529779,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/r/pages/image70.adoc","line":133},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"dropping cells from incomplete row detected end of table"}
{"level":"warn","time":1751477529849,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/r/pages/image84.adoc","line":7},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected A, got H"}
{"level":"warn","time":1751477529849,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/r/pages/image84.adoc","line":31},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected B, got H"}
{"level":"warn","time":1751477529850,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/r/pages/image84.adoc","line":44},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected C, got G"}
{"level":"warn","time":1751477529850,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/r/pages/image84.adoc","line":45},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected D, got H"}
{"level":"warn","time":1751477529850,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/r/pages/image84.adoc","line":46},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected E, got W"}
{"level":"warn","time":1751477529886,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/r/pages/image92.adoc","line":23},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"unterminated literal block"}
{"level":"warn","time":1751477529941,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/ROOT/pages/exported/image116.adoc","line":4},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected 1, got 407"}
{"level":"warn","time":1751477529941,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/ROOT/pages/exported/image116.adoc","line":10},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected 2, got 411"}
{"level":"warn","time":1751477529989,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/r/pages/exported/image116.adoc","line":4},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected 1, got 407"}
{"level":"warn","time":1751477529990,"name":"asciidoctor","file":{"path":"/home/kurt/immanuel-adoc/modules/r/pages/exported/image116.adoc","line":10},"source":{"url":"https://github.com/kurt-krueckeberg/immanuel-adoc.git","local":"/home/kurt/immanuel-adoc/.git","worktree":"/home/kurt/immanuel-adoc","refname":"main","reftype":"branch"},"msg":"list item index: expected 2, got 411"}
